Added 'request' as optional dependency.
Compiling following less code:
@import (less) url(http://example.com/somefile.less);

Will fail with if npm 'request' package is not installed:
FileError: optional dependency 'request' required to import over http(s)